# Global proxy configuration for tips service
ProxyPass /dbtips/ http://127.0.0.1:3432/plain/
ProxyPassReverse /dbtips/ http://127.0.0.1:3432/plain/
ProxyPass /plain/ http://127.0.0.1:3432/plain/
ProxyPassReverse /plain/ http://127.0.0.1:3432/plain/
